language: node_js
services: mongodb
node_js:
  - "8"
  - "9"
before_install:
- npm install -g mocha standard
script:
- npm run standard
- npm run test:config:nedb
- npm run test
- npm run test:config:mongodb
- npm run test
